import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import { useSelector } from 'react-redux';
import { ToastContainer } from 'react-toastify';
import Spinner from './utils/Spinner';

const DashLayout = ({ children, title }) => {
    const spinner = useSelector((state) => state.spinner);
    return (
        <>
            {' '}
            <Head>
                <meta charset="UTF-8" />
                <meta http-equiv="X-UA-Compatible" content="IE=7" />
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <meta name="description" content="Generated by create next app" />
                <meta name="description" content="Trello frontend application" />
                <meta name="Author" content="Forhadul Islam" />
                <title>Dashboard</title>
                <link rel="icon" sizes="30X30" href="./icon/application-icon.svg" />
                <link rel="icon" sizes="30X30" href="./icon/application-icon-80X80.svg" />
                <link rel="icon" sizes="30X30" href="./icon/application-icon-120X120.svg" />
            </Head>
            <ToastContainer />
            {spinner && <Spinner />}
            <div className=" p-3 text-slate-50 w-full bg-[#3056d3] shadow">
                <h1 className=" text-4xl text-center text-slate-50 title break-words cursor-pointer">
                    <Link href={'/'}>{title ? title : 'React Trellor App'}</Link>
                </h1>
            </div>
            <div className="container m-auto">
                <div className="container pt-4 pb-6 m-auto">{children}</div>
            </div>
        </>
    );
};

export default DashLayout;
