import Head from 'next/head';
import React from 'react';
import { useSelector } from 'react-redux';
import { ToastContainer } from 'react-toastify';
import Footer from './Footer/Footer';
import NavBar from './Nav/NavBar';
import Spinner from './utils/Spinner';

const Layout = ({ children, title }) => {
    const spinner = useSelector((state) => state.spinner);

    return (
        <>
            <Head>
                <meta charset="UTF-8" />
                <meta http-equiv="X-UA-Compatible" content="IE=7" />
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <meta name="description" content="Generated by create next app" />
                <meta name="description" content="Trello frontend application" />
                <meta name="Author" content="Forhadul Islam" />
                <title>{title ? title : ''} </title>
                <link rel="icon" sizes="30X30" href="./icon/application-icon.svg" />
                <link rel="icon" sizes="30X30" href="./icon/application-icon-80X80.svg" />
                <link rel="icon" sizes="30X30" href="./icon/application-icon-120X120.svg" />
            </Head>
            <ToastContainer />
            {spinner && <Spinner />}
            <NavBar />
            <div className="container m-auto">{children}</div>
            <Footer />
        </>
    );
};

export default React.memo(Layout);
